import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "top-[0%]",
    "top-[25%]",
    "top-[50%]",
    "top-[75%]",
    "left-[0%]",
    "left-[25%]",
    "left-[50%]",
    "left-[75%]",
    "bottom-[0%]",
    "bottom-[1%]",
    "bottom-[2%]",
    "bottom-[3%]",
    "bottom-[4%]",
    "bottom-[5%]",
    "bottom-[6%]",
    "bottom-[7%]",
    "bottom-[8%]",
    "bottom-[9%]",
    "bottom-[10%]",
    "bottom-[11%]",
    "bottom-[12%]",
    "bottom-[13%]",
    "bottom-[14%]",
    "bottom-[15%]",
    "bottom-[16%]",
    "bottom-[17%]",
    "bottom-[18%]",
    "bottom-[19%]",
    "bottom-[20%]",
    "bottom-[21%]",
    "bottom-[22%]",
    "bottom-[23%]",
    "bottom-[24%]",
    "bottom-[25%]",
    "bottom-[26%]",
    "bottom-[27%]",
    "bottom-[28%]",
    "bottom-[29%]",
    "bottom-[30%]",
    "bottom-[31%]",
    "bottom-[32%]",
    "bottom-[33%]",
    "bottom-[34%]",
    "bottom-[35%]",
    "bottom-[36%]",
    "bottom-[37%]",
    "bottom-[38%]",
    "bottom-[39%]",
    "bottom-[40%]",
    "bottom-[41%]",
    "bottom-[42%]",
    "bottom-[43%]",
    "bottom-[44%]",
    "bottom-[45%]",
    "bottom-[46%]",
    "bottom-[47%]",
    "bottom-[48%]",
    "bottom-[49%]",
    "bottom-[50%]",
    "bottom-[51%]",
    "bottom-[52%]",
    "bottom-[53%]",
    "bottom-[54%]",
    "bottom-[55%]",
    "bottom-[56%]",
    "bottom-[57%]",
    "bottom-[58%]",
    "bottom-[59%]",
    "bottom-[60%]",
    "bottom-[61%]",
    "bottom-[62%]",
    "bottom-[63%]",
    "bottom-[64%]",
    "bottom-[65%]",
    "bottom-[66%]",
    "bottom-[67%]",
    "bottom-[68%]",
    "bottom-[69%]",
    "bottom-[70%]",
    "bottom-[71%]",
    "bottom-[72%]",
    "bottom-[73%]",
    "bottom-[74%]",
    "bottom-[75%]",
    "bottom-[76%]",
    "bottom-[77%]",
    "bottom-[78%]",
    "bottom-[79%]",
    "bottom-[80%]",
    "bottom-[81%]",
    "bottom-[82%]",
    "bottom-[83%]",
    "bottom-[84%]",
    "bottom-[85%]",
    "bottom-[86%]",
    "bottom-[87%]",
    "bottom-[88%]",
    "bottom-[89%]",
    "bottom-[90%]",
    "bottom-[91%]",
    "bottom-[92%]",
    "bottom-[93%]",
    "bottom-[94%]",
    "bottom-[95%]",
    "bottom-[96%]",
    "bottom-[97%]",
    "bottom-[98%]",
    "bottom-[99%]",
    "bottom-[100%]",
    "ml-1",
    "ml-2",
    "ml-3",
    "ml-4",
    "ml-5",
    "bg-connections-yellow",
    "bg-connections-green",
    "bg-connections-blue",
    "bg-connections-purple",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      backgroundColor: {
        "connections-button": "rgb(239, 239, 230)",
        "connections-button-active": "rgb(90, 89, 78)",
        "connections-yellow": "rgb(var(--connections-yellow))",
        "connections-green": "rgb(var(--connections-green))",
        "connections-blue": "rgb(var(--connections-blue))",
        "connections-purple": "rgb(var(--connections-purple))",
        base: "rgb(var(--background-start-rgb))",
      },
      colors: {
        "connections-button": "rgb(0, 0, 0)",
        "connections-button-active": "rgb(255, 255, 255)",
      },
      width: {
        "120": "30rem",
        "88": "22rem",
      },
      top: {
        "20": "5rem",
        "30": "7.5rem",
        "40": "10rem",
        "50": "12.5rem",
      },
      left: {
        "20": "5rem",
        "30": "7.5rem",
        "40": "10rem",
        "50": "12.5rem",
      },
      animation: {
        jiggleIncorrect: "jiggleIncorrect .25s ease-in-out infinite",
        jiggleCorrect: "jiggleCorrect 400ms ease-in-out",
        popIn: "popIn 500ms ease-in-out, fadeIn 500ms ease-in-out",
        slideDown: "slideDown 500ms ease-in-out, fadeIn 500ms ease-in-out",
      },
      keyframes: {
        jiggleIncorrect: {
          "0%, 100%": { transform: "translateX(0px)" },
          "33%": { transform: "translateX(4px)" },
          "77%": { transform: "translateX(-4px)" },
        },
        jiggleCorrect: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        popIn: {
          "0%": { transform: "scale(.8)" },
          "50%": { transform: "scale(1.1)" },
          "100%": { transform: "scale(1)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideDown: {
          "0%": { transform: "translateY(-100%)" },
          "50%": { transform: "translateY(10%)" },
          "100%": { transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
